.gitlab-ci.yml
stages:

build

test

deploy

build_image:
stage: build
script:
- docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG -f ./infra/docker/Dockerfile.assistant .
- docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
only:
- tags

run_tests:
stage: test
script:
- python3 -m venv venv
- source venv/bin/activate
- pip install -r GenAI_Factory/requirements.txt
- pytest GenAI_Factory/domain_models/genai_assistant/tests/
only:
- main

deploy_prod:
stage: deploy
script:
- echo "Deploying to production..."
- kubectl apply -f ./infra/k8s/
only:
- tags